module.exports = [
	{ name: 'Alternative', tmID: 'KnvZfZ7vAvv', category: 'MUSIC' },
	{ name: 'Blues', tmID: 'KnvZfZ7vAvd', category: 'MUSIC' },
	{ name: 'Classical', tmID: 'KnvZfZ7vAeJ', category: 'MUSIC' },
	{ name: 'Country', tmID: 'KnvZfZ7vAv6', category: 'MUSIC' },
	{ name: 'Dance/Electronic', tmID: 'KnvZfZ7vAvF', category: 'MUSIC' },
	{ name: 'Folk', tmID: 'KnvZfZ7vAva', category: 'MUSIC' },
	{ name: 'Hip Hop/Rap', tmID: 'KnvZfZ7vAv1', category: 'MUSIC' },
	{ name: 'Jazz', tmID: 'KnvZfZ7vAvE', category: 'MUSIC' },
	{ name: 'Metal', tmID: 'KnvZfZ7vAvt', category: 'MUSIC' },
	{ name: 'New Age', tmID: 'KnvZfZ7vAvn', category: 'MUSIC' },
	{ name: 'Pop', tmID: 'KnvZfZ7vAev', category: 'MUSIC' },
	{ name: 'R&B', tmID: 'KnvZfZ7vAee', category: 'MUSIC' },
	{ name: 'Reggae', tmID: 'KnvZfZ7vAed', category: 'MUSIC' },
	{ name: 'Rock', tmID: 'KnvZfZ7vAeA', category: 'MUSIC' },

	{ name: 'Baseball', tmID: 'KnvZfZ7vAdv', category: 'SPORTS' },
	{ name: 'Basketball', tmID: 'KnvZfZ7vAde', category: 'SPORTS' },
	{ name: 'Boxing', tmID: 'KnvZfZ7vAdA', category: 'SPORTS' },
	{ name: 'Equestrian', tmID: 'KnvZfZ7vAd1', category: 'SPORTS' },
	{ name: 'Football', tmID: 'KnvZfZ7vAdE', category: 'SPORTS' },
	{ name: 'Golf', tmID: 'KnvZfZ7vAdt', category: 'SPORTS' },
	{ name: 'Hockey', tmID: 'KnvZfZ7vAdI', category: 'SPORTS' },
	{ name: 'Soccer', tmID: 'KnvZfZ7vA7E', category: 'SPORTS' },
	{ name: 'Tennis', tmID: 'KnvZfZ7vAAv', category: 'SPORTS' },

	{ name: 'Circus', tmID: 'KnvZfZ7v7n1', category: 'ARTS_THEATRE' },
	{ name: 'Classical', tmID: 'KnvZfZ7v7nJ', category: 'ARTS_THEATRE' },
	{ name: 'Comedy', tmID: 'KnvZfZ7vAe1', category: 'ARTS_THEATRE' },
	{ name: 'Dance', tmID: 'KnvZfZ7v7nI', category: 'ARTS_THEATRE' },
	{ name: 'Performance Art', tmID: 'KnvZfZ7v7l6', category: 'ARTS_THEATRE' },
	{ name: 'Theatre', tmID: 'KnvZfZ7v7l1', category: 'ARTS_THEATRE' },

	{ name: 'Comedy', tmID: 'KnvZfZ7vAA1', category: 'MISCELLANEOUS' },
	{ name: 'Fairs & Festival', tmID: 'KnvZfZ7vAeE', category: 'MISCELLANEOUS' },
	{ name: 'Food & Drink', tmID: 'KnvZfZ7vAAI', category: 'MISCELLANEOUS' },
	{ name: 'Ice Shows', tmID: 'KnvZfZ7v7lI', category: 'MISCELLANEOUS' },
];
